[package]
name = "rcli"
authors = ["Tyr Chen <Sonder.QiCat@outlook.com>"]
version = "1.0.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.228", features = ["derive"] }
chrono = "0.4.43"
anyhow = "1.0.100"
serde_json = "1.0.149"
